# Generated by Django 4.2 on 2026-04-13 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ILES', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academic_supervisor_feedback',
            name='academic_supervisor',
            field=models.ForeignKey(limit_choices_to={'role': 'academic'}, on_delete=django.db.models.deletion.CASCADE, related_name='academic_feedback_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='internship_placement',
            name='academic_supervisor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'academic'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_supervised', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='internship_placement',
            name='workplace_supervisor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'workplace'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workplace_supervised', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supervisor_feedback',
            name='supervisor',
            field=models.ForeignKey(limit_choices_to={'role': 'workplace'}, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supervisor_feedback',
            name='weekly_log',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_feedback', to='ILES.weekly_log'),
        ),
        migrations.AlterField(
            model_name='weekly_log',
            name='submitted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
