# Generated by Django 6.0.3 on 2026-03-23 19:06

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Internship_Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed')], default='pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Weekly_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField()),
                ('activities', models.TextField()),
                ('challenges', models.TextField(blank=True)),
                ('learnings', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_logs', to='ILES.internship_placement')),
            ],
        ),
        migrations.CreateModel(
            name='Weighted_Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisor_score', models.FloatField()),
                ('academic_score', models.FloatField()),
                ('final_score', models.FloatField()),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('placement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='weighted_scores', to='ILES.internship_placement')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('student', 'Student'), ('workplace', 'Workplace Supervisor'), ('academic', 'Academic Supervisor'), ('admin', 'Internship Administrator')], default='student', max_length=30)),
                ('department', models.CharField(max_length=100)),
                ('staff_number', models.CharField(blank=True, max_length=20, null=True)),
                ('student_number', models.CharField(blank=True, max_length=20, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor_Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField()),
                ('supervisor_score', models.PositiveIntegerField()),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('weekly_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='ILES.weekly_log')),
                ('supervisor', models.ForeignKey(limit_choices_to={'role': ['workplace_supervisor']}, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_given', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('issue_type', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='ILES.internship_placement')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_issues', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='internship_placement',
            name='academic_supervisor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'academic_supervisor'}, max_length=255, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_supervised', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='internship_placement',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_placements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='internship_placement',
            name='workplace_supervisor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'workplace_supervisor'}, max_length=255, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workplace_supervised', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Academic_Supervisor_Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField()),
                ('academic_score', models.PositiveIntegerField()),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_feedbacks', to='ILES.internship_placement')),
                ('academic_supervisor', models.ForeignKey(limit_choices_to={'role': ['academic_supervisor']}, on_delete=django.db.models.deletion.CASCADE, related_name='academic_feedback_given', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
