# Generated by Django 6.0.3 on 2026-04-18 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ILES', '0002_log'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='log',
            new_name='Student_log',
        ),
        migrations.AlterField(
            model_name='academic_supervisor_feedback',
            name='academic_supervisor',
            field=models.ForeignKey(limit_choices_to={'role': 'academic_supervisor'}, on_delete=django.db.models.deletion.CASCADE, related_name='academic_feedback_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='internship_placement',
            name='academic_supervisor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'academic_supervisor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_supervised', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='internship_placement',
            name='workplace_supervisor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'workplace_supervisor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workplace_supervised', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supervisor_feedback',
            name='supervisor',
            field=models.ForeignKey(limit_choices_to={'role': 'workplace_supervisor'}, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='weekly_log',
            unique_together={('placement', 'week_number')},
        ),
    ]
