# Generated by Django 6.0.3 on 2026-04-21 16:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ILES', '0003_rename_log_student_log_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_log',
            name='attatchment',
            field=models.FileField(blank=True, null=True, upload_to='log_attachments/'),
        ),
        migrations.AddField(
            model_name='student_log',
            name='challenges',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student_log',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='student_log',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_log',
            name='supervisor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'workplace_supervisor'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student_log',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supervisor_feedback',
            name='placement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_feedbacks', to='ILES.internship_placement'),
        ),
        migrations.AddField(
            model_name='supervisor_feedback',
            name='student_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_feedbacks', to='ILES.student_log'),
        ),
        migrations.AddField(
            model_name='weekly_log',
            name='feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='weekly_log',
            name='supervisor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'workplace_supervisor'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weekly_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student_log',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='ILES.internship_placement'),
        ),
        migrations.AlterField(
            model_name='weekly_log',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
    ]
