# Generated by Django 6.0.3 on 2026-04-23 13:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ILES', '0004_student_log_attatchment_student_log_challenges_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weekly_log',
            name='feedback',
        ),
        migrations.AlterField(
            model_name='weekly_log',
            name='submitted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
