# Generated by Django 6.0.3 on 2026-05-06 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ILES', '0005_remove_weekly_log_feedback_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_log',
            old_name='attatchment',
            new_name='attachment',
        ),
        migrations.AlterField(
            model_name='academic_supervisor_feedback',
            name='academic_supervisor',
            field=models.ForeignKey(limit_choices_to={'role': 'academic'}, on_delete=django.db.models.deletion.CASCADE, related_name='academic_feedback_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='internship_placement',
            name='academic_supervisor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'academic'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_supervised', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='internship_placement',
            name='workplace_supervisor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'workplace'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workplace_supervised', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student_log',
            name='supervisor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'workplace'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supervisor_feedback',
            name='supervisor',
            field=models.ForeignKey(limit_choices_to={'role': 'workplace'}, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='weekly_log',
            name='supervisor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'workplace'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weekly_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(max_length=200)),
                ('target_id', models.IntegerField(blank=True, null=True)),
                ('target_type', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
