# Generated by Django 6.0.3 on 2026-05-07 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ILES', '0006_rename_attatchment_student_log_attachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
