# Generated by Django 6.0.3 on 2026-05-14 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ILES', '0007_alter_customuser_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_log',
            name='supervisor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'workplace'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='weekly_log',
            name='supervisor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'workplace'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weekly_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
