# Generated by Django 6.0.3 on 2026-06-07 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ILES', '0008_alter_student_log_supervisor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship_placement',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='notification',
            name='message',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
