# Generated by Django 6.0.3 on 2026-06-13 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ILES', '0010_alter_academic_supervisor_feedback_academic_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship_placement',
            name='student_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='internship_placement',
            name='workplace_supervisor_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
