# Generated by Django 6.0.3 on 2026-06-14 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ILES', '0011_internship_placement_student_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekly_log',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
